### ISSUE TITLE
Local server not receiving any request on identity handler or execute handler

### ISSUE THREAD

**Issue by arihantdaga** [actions-on-google/smart-home-local#12]
<img width="1440" alt="Screen Shot 2019-10-08 at 2 22 24 AM" src="https://user-images.githubusercontent.com/4976460/66347674-834e4880-e972-11e9-9890-f27a102234e8.png">
I have setup everything right according to the readme. And initially i got one or 2 requests in the identifyhandler in which i threw error. But now no matter what i do, i am not seeing any request coming to the local server. Even though google home is loading the local server web page. 
Should i do something else ? or this is a bug with google home itself ? 

Also this is my response in the sync request - 
```
{
    "requestId": "12942802761996814011",
    "payload": {
        "agentUserId": "1234",
        "devices": [
            {
                "id": "1xj9",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "Smart Switch"
                    ],
                    "name": "Smart Switch",
                    "nicknames": [
                        "smart switch"
                    ]
                },
                "deviceInfo": {
                    "manufacturer": "L",
                    "model": "L",
                    "hwVersion": "1.0.0",
                    "swVersion": "2.0.0"
                },
                "willReportState": true,
                "otherDeviceIds": [
                    {
                        "deviceId": "5678"
                    }
                ]
            },
            {
                "id": "22bn",
                "type": "action.devices.types.OUTLET",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "Smart Outlet"
                    ],
                    "name": "Smart Outlet",
                    "nicknames": [
                        "smart plug"
                    ]
                },
                "deviceInfo": {
                    "manufacturer": "L",
                    "model": "L",
                    "hwVersion": "1.0.0",
                    "swVersion": "2.0.0"
                },
                "willReportState": true,
                "otherDeviceIds": [
                    {
                        "deviceId": "1234"
                    }
                ]
            }
        ]
    }
}
```

**Comment by devunwired** [comment]
What discovery method do you use in your scan configuration? If you are using UDP discovery, do your local devices see the periodic UDP broadcast from the Home device?

**Comment by arihantdaga** [comment]
I wanted to make an example using mdns discovery and contribute.
I setup mdns discovery in actions console. 
<img width="917" alt="Screen Shot 2019-10-08 at 10 12 13 AM" src="https://user-images.githubusercontent.com/4976460/66367979-22dffb00-e9b4-11e9-8eb7-954772ad284d.png">
And i started advertising on mdns also using an esp8266.
I noticed now, that identify request is not triggered unless i change the wifi network name itself. 
When i changed the wifi name, it again triggered once. After that its NOT calling it again whenever i ask for sync my devices or unlink/link my account or if i restart the google home.

**Comment by arihantdaga** [comment]
I got it, i re read the documentation, it says `The IDENTIFY handler will be triggered when the Google Home or Google Nest device reboots and sees unverified devices.`
I have one more doubt regarding mdns. 
I tried using mdns in app.ts for fetching info from local devices, but it fails to compile when i am using mdns or mdns-js. (I guess, maybe they are not meant to run on browser ? and only in NodeJs ?)

Will it be right approach for supporting devices based on mdns ? or i am headed in wrong direction. @devunwired  Will be glad if you know something and you can point me in right direction.

**Comment by devunwired** [comment]
Correct, the `IDENTIFY` handler is only called until you have successfully identified the device that was discovered on the local network.

> I tried using mdns in app.ts for fetching info from local devices, but it fails to compile when i am using mdns or mdns-js.

Depending on what you are trying to accomplish, this probably isn't the right approach. The compilation issue is probably because you need to use a tool like Webpack to compile using a library built for Node.js so it can run within the Chrome environment.

However, since the discovery process handles all the mDNS discovery (and provides you the results in the `mdnsScanData`), you shouldn't need to use an mDNS library directly to get any of the data broadcast by the device. The `TXT` record data will all be present in the `additionals` property of the scan data provided to your `IDENTIFY` handler.

Once the device has been discovered and identified, use the [DataFlow](https://developers.google.com/assistant/smarthome/reference/local/modules/smarthome.dataflow) component of the SDK to communicate with it using TCP/UDP/HTTP.

**Side Note:** I would recommend asking these more general development questions on StackOverflow using the [google-smart-home](https://stackoverflow.com/questions/tagged/google-smart-home) tag so they get more visibility.
